export const HACKATHON_START_DATE = new Date(process.env.NEXT_PUBLIC_HACKATHON_START_DATE || "2025-02-17");
export const HACKATHON_END_DATE = new Date(process.env.NEXT_PUBLIC_HACKATHON_END_DATE || "2025-03-18");

export const EVENT_REGISTRATION_START_DATE = new Date(process.env.NEXT_PUBLIC_EVENT_REGISTRATION_START_DATE || "2025-02-11");
export const EVENT_REGISTRATION_END_DATE = new Date(process.env.NEXT_PUBLIC_EVENT_REGISTRATION_END_DATE || "2025-02-12");
